name: Acceptance Tests

on:
  push:
    paths:
      - ".github/workflows/acceptance.yml"
      - "backend/**"
      - "frontend/**"


jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            plone/ploneconf-backend
          tags: |
            type=sha
            type=raw,value=acceptance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile.acceptance
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/backend-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: /tmp/backend-image.tar

  build-frontend:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            plone/ploneconf-frontend
          tags: |
            type=sha
            type=raw,value=acceptance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/frontend-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: /tmp/frontend-image.tar

  acceptance-test:
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - build-frontend
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Images
        uses: actions/download-artifact@v2
        with:
          path: /tmp

      - name: Load Docker Images
        run: |
          docker load --input /tmp/backend/backend-image.tar
          docker load --input /tmp/frontend/frontend-image.tar

      - name: Install Cypress
        run: npm i cypress

      - name: Cypress acceptance tests
        uses: cypress-io/github-action@v2
        env:
          BABEL_ENV: production
          CYPRESS_RETRIES: 2
        with:
          parallel: false
          browser: chrome
          group: Integration tests
          spec: cypress/integration/*.js
          working-directory: frontend
          install: false
          start: |
            docker compose -f cypress/compose.yml up
          wait-on: 'npx wait-on --httpTimeout 20000 http-get://localhost:55001/plone http://localhost:3000'
