name: Acceptance Tests

on:
  push:
    paths:
      - ".github/workflows/acceptance.yml"
      - "backend/**"
      - "frontend/**"


jobs:

  build-backend:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            plone/ploneconf-backend
          tags: |
            type=sha
            type=raw,value=acceptance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile.acceptance
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/backend-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-image
          path: /tmp/backend-image.tar

  build-frontend:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            plone/ploneconf-frontend
          tags: |
            type=sha
            type=raw,value=acceptance

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          file: backend/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/frontend-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-image
          path: /tmp/frontend-image.tar

  acceptance-test:
    runs-on: ubuntu-latest
    needs:
      - build-backend
      - build-frontend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download Backend Image
        uses: actions/download-artifact@v2
        with:
          name: backend-image
          path: /tmp

      - name: Download Frontend Image
        uses: actions/download-artifact@v2
        with:
          name: frontend-image
          path: /tmp

      - name: Load Docker Images
        run: |
          docker load --input /tmp/backend-image.tar
          docker load --input /tmp/frontend-image.tar
          docker image ls -a
